### ISSUE TITLE
Ref doesn't work with optional keys

### ISSUE THREAD

**Issue by brianle1301** [vlucas/vlid#6]
Consider the following example: 
```
v.object({
  a: v.number().min(v.ref('b')).required(),
  b: v.number().default(5),
}).validate({
  a: 6,
}); // Must greater or equal to undefined
```
However, if we swap a and b
 ```
v.object({
  b: v.number().default(5),
  a: v.number().min(v.ref('b')).required(),
}).validate({
  a: 6,
}); // Pass
```

**Expected behaviour**
Both should produce the same result as the second one

**Comment by vlucas** [comment]
Weird that the order even matters. I am looking into this.

**Comment by brianle1301** [comment]
@vlucas Hey. I had a look at the source of Yup and joi and it seemed like they both sort their rules topologically, making sure that the dependency is validated before the dependents. Not 100% sure how this is done in details, but my naive approach would be to unwrap the object schema and sort the keys.

**Comment by vlucas** [comment]
Well internally the `ref` is a closure with deferred evaluation, so it honestly should not matter the order. All the other rules would have been defined by the time it runs (on `validate`). I will dig into it a bit more later tonday.

**Comment by vlucas** [comment]
Found it and fixed.

**Comment by vlucas** [comment]
Please upgrade to `v1.0.4` for the new code.

**Comment by brianle1301** [comment]
@vlucas Lovely, thank you
